- Cargo.lock
- Cargo.toml
- src/application.rs
- src/commands/start.rs
- src/config.rs
- src/error.rs
- src/lib.rs
Use a hyphen for consistency with the other features
> Rename `tx-signer` Cargo feature

- Cargo.lock
- Cargo.toml
- src/tx_signer.rs
Includes some small log formatting tweaks
> Bump `stdtx` to v0.2

- Cargo.lock
- Cargo.toml
Release notes: https://github.com/iqlusioninc/yubihsm.rs/pull/61
> Bump `yubihsm` to v0.34.0

- README.txsigner.md
- src/commands/yubihsm/keys/list.rs
Makes it easier to determine which key is which
> yubihsm: show labels when listing keys

- src/tx_signer.rs
This gets both the CheckTx and DeliverTx results
> tx_signer: use `broadcast_tx_commit`

- Cargo.lock
- Cargo.toml
This is the first alpha release that works with Tendermint v0.34
> v0.10.0-alpha3

- CHANGELOG.md
Note: this is not a release, just updating the changelog.
Closes #278
> Add CHANGELOG.md entries for v0.10.0 (UNRELEASED)

- src/commands/init/config_builder.rs
- src/commands/init/networks.rs
- src/commands/init/templates/networks/sentinelhub.toml
- src/commands/init/templates/schema/sentinelhub.toml
> Add Sentinel config

- .github/workflows/ci.yml
It's quite a bit out-of-date and presently failing
> .github: update codecov config

- src/signing.rs
Adds tests which use the same fixtures as the integration tests, but compare to a reference vector for a serialized message.
This will help prevent breakages during refactoring.
> Add `SignedMsg` unit tests

- README.yubihsm.md
I've described the steps that I used for migrating existing validator to use HSM for signing blocks. Should be useful as a checklist-style guide for newbies or something.
Not sure if it belongs here or in the new file though.
> Add step-by-step guide on integrating tmkms with YubiHSM2 with existing validator

- Cargo.lock
- Cargo.toml
> v0.14.0-pre.0

- src/privval.rs
Refs https://github.com/iqlusioninc/tmkms/pull/857#issuecomment-1973652356
> fix(privval): sign extension even when it's empty

- tmkms-p2p/src/protocol.rs
- tmkms-p2p/src/secret_connection.rs
This factors I/O related functionality into the `secret_connection` module, which should make it easier to implement async later.
> tmkms-p2p: move I/O functions to `secret_connection`

- Cargo.lock
- Cargo.toml
- tmkms-p2p/CHANGELOG.md
- tmkms-p2p/Cargo.toml
- tmkms-p2p/LICENSE
> tmkms-p2p v0.1.0

- Cargo.lock
- tmkms-p2p/Cargo.toml
- tmkms-p2p/src/lib.rs
- tmkms-p2p/src/msg_traits.rs
- tmkms-p2p/src/secret_connection.rs
- tmkms-p2p/tests/secret_connection.rs
Runs a simple ping/pong server
> tmkms-p2p: add basic `SecretConnection` integration test

- tmkms-p2p/tests/secret_connection.rs
Excercises the logic in `ReadMsg` and the `Write` impl on `SecretConnection` for handling protos which span multiple message frames.
> tmkms-p2p: use randomized messages in integration tests

- tmkms-p2p/src/msg_traits.rs
Extracts a function for computing the total length of a Protobuf based on the length prefix
> tmkms-p2p: extract `decode_msg_length`

- tmkms-p2p/src/secret_connection.rs
This will complicate further attempts to clean up the low-level I/O and buffering.
It can potentially be added back when we're done, but isn't needed by tmkms nor is it currently tested.
The best path forward for this sort of functionality is a prospective async implementation.
> tmkms-p2p: remove `SecretConnection::split`

- Cargo.lock
- Cargo.toml
- tmkms-p2p/CHANGELOG.md
- tmkms-p2p/Cargo.toml
- tmkms-p2p/src/lib.rs
- Initial async support (#1067, #1069)
- `SecretConnection::split` (#1077)
- `SecretConnection::remote_pubkey` => `peer_public_key` (#1071)
- `AsyncSecretConnection::remote_pubkey` => `peer_public_key` (#1071)
> tmkms-p2p v0.6.0

- Cargo.lock
- Cargo.toml
Includes switch to `cometbft-p2p` v0.1.0
> v0.15.0-pre.6
